shared_context 'Database initialization and connection test' do
  def exec_sql(sql)
    ::ActiveRecord::Base.connection.execute(sql)
  end

  def populate_accounts_table
    exec_sql <<~SQL
      INSERT INTO accounts VALUES
      (1, 'alice', 1000.0),
      (2, 'bob', 100.0),
      (3, 'bob', 900.0)
    SQL
  end

  before do
    ::ActiveRecord::Base.establish_connection(
      adapter: 'postgresql',
      host: 'localhost',
      username: 'username',
      password: '123',
      database: 'pg_isolation_test'
    )
    exec_sql <<~SQL
      DROP TABLE IF EXISTS accounts;
      CREATE TABLE accounts(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        client text,
        amount numeric
      )
    SQL
  end

  after do
    ::ActiveRecord::Base.connection.close
  end

  it 'Returns list of database tables' do
    expect(::ActiveRecord::Base.connection.tables).to be_present
  end
end
