test:
  primary:
    adapter: postgresql
    database: <%= ENV["POSTGRES_DB"] %>
    host: <%= ENV["POSTGRES_HOST"] %>
    port: <%= ENV["POSTGRES_PORT"] %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
