require 'pry'
require_relative 'spec_helper.rb'

shared_context 'Database initialization' do
  def exec_sql(sql)
    ::ActiveRecord::Base.connection.execute(sql)
  end

  def populate_accounts_table
    exec_sql <<~SQL
      INSERT INTO accounts VALUES
      (1, 'alice', 1000.0),
      (2, 'bob', 100.0),
      (3, 'bob', 900.0)
    SQL
  end

  def initialize_table
    exec_sql <<~SQL
      DROP TABLE IF EXISTS accounts;
      CREATE TABLE accounts(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        client text,
        amount numeric
      )
    SQL
  end

  def establish_connection
    ::ActiveRecord::Base.establish_connection(
      adapter: 'postgresql',
      host: '0.0.0.0',
      username: 'postgres',
      password: 'postgres',
      database: 'pg_isolation_test'
    )
    ActiveRecord::Base.logger = ActiveSupport::Logger.new('log/test.log')
  end

  before do
    establish_connection
    initialize_table
  end

  after do
    ::ActiveRecord::Base.connection.close
  end
end
